name: break_infinity
description: BigInt and double replacement that can hold up to 1e9e15 that focuses on speed.
version: 1.0.3
repository: https://github.com/exoad/break_infinity.dart

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
