name: big_double
description: High performing BigInt & double replacement that can hold more than 1^308 and up to 10^^308
version: 1.0.2
repository: https://github.com/exoad/big_double.dart

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
