name: break_infinity
description: BigInt and double replacement that can hold more than 1e308 and up to 1e9e15.
version: 1.0.4
repository: https://github.com/exoad/break_infinity.dart

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
