name: big_double
description: High-performance BigInt and double replacement that allows for upwards of 10^10^308
version: 1.0.1
repository: https://github.com/exoad/big_double.dart

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
