name: run tests

on:
  push:
    branches: ["main"]
    paths:
      - "!/.github/**"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  initial_prechecks:
    name: Prechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Analyze Source
        run: |
          dart pub get
          dart analyze --fatal-infos
  web:
    name: Run Web Tests (NodeJS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze --fatal-infos
      - name: Test
        run: dart test -pnode --chain-stack-traces --reporter=failures-only --js-trace --file-reporter "json:test_results/reports_web.json"
      - name: Upload web test results
        uses: actions/upload-artifact@v3
        with:
          name: WebTestResults
          path: test_results/reports_web.json
          retention-days: 3
  native:
    name: Run Native Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze --fatal-infos
      - name: Test
        run: dart test --chain-stack-traces --reporter=failures-only --file-reporter "json:test_results/reports_native.json"
      - name: Upload native test results
        uses: actions/upload-artifact@v3
        with:
          name: NativeTestResults
          path: test_results/reports_native.json
          retention-days: 3
